source 'https://rubygems.org'

gem 'puma'
gem 'rerun'
gem 'roda'
gem 'tilt'
gem 'sucker_punch'
gem 'dotenv'
gem 'ruby-trello'
gem 'mailgun-ruby'
gem 'addressable'
gem 'pry'
gem 'bugsnag'
gem 'cloudflare', :git => 'https://github.com/sonicdes/cloudflare.git', :branch => 'master'
